use spring_xingou;
CREATE TABLE user (
  uid int NOT NULL AUTO_INCREMENT,
  uname varchar(20) NOT NULL,
  passwd varchar(20) NOT NULL,
  email varchar(30) NOT NULL,
  phone varchar(20) NOT NULL,
  lastlogin varchar(20),
  usertype INT NOT NULL ,
  PRIMARY KEY (uid),
  UNIQUE KEY uname (uname)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE userinfo (
  id int NOT NULL AUTO_INCREMENT,
  uid int not null,
  height varchar(10) DEFAULT NULL,
  weight varchar(10) DEFAULT NULL,
  gender char(1) DEFAULT NULL,
  age varchar(10) DEFAULT NULL,
  iden varchar(18) DEFAULT NULL,
  addr varchar(45) DEFAULT NULL,
  nationality varchar(5) DEFAULT NULL,
  company varchar(30) DEFAULT NULL,
  edu varchar(10) DEFAULT NULL,
  job varchar(25) DEFAULT NULL,
  marry varchar(5) DEFAULT NULL,
  bloodtype varchar(5) DEFAULT NULL,
  selfevaluate varchar(5) DEFAULT NULL,
  mentality varchar(3) DEFAULT NULL,
  allergy varchar(20) DEFAULT NULL,
  desease1 varchar(15) DEFAULT NULL,
  desease2 varchar(15) DEFAULT NULL,
  desease3 varchar(15) DEFAULT NULL,
  deseasemore varchar(200) DEFAULT NULL,
  dtime1 varchar(20) DEFAULT NULL,
  dtime2 varchar(20) DEFAULT NULL,
  dtime3 varchar(20) DEFAULT NULL,
  operation1 varchar(30) DEFAULT NULL,
  operation2 varchar(30) DEFAULT NULL,
  operation3 varchar(30) DEFAULT NULL,
  operationmore varchar(200) DEFAULT NULL,
  otime1 varchar(20) DEFAULT NULL,
  otime2 varchar(20) DEFAULT NULL,
  otime3 varchar(20) DEFAULT NULL,
  f1desease varchar(30) DEFAULT NULL,
  f2desease varchar(30) DEFAULT NULL,
  f3desease varchar(30) DEFAULT NULL,
  f4desease varchar(30) DEFAULT NULL,
  inheridesease varchar(30) DEFAULT NULL,
  exefre varchar(7) DEFAULT NULL,
  exeway varchar(10) DEFAULT NULL,
  exetime varchar(5) DEFAULT NULL,
  eathabit varchar(6) DEFAULT NULL,
  smokestatus varchar(5) DEFAULT NULL,
  smokeamount varchar(5) DEFAULT NULL,
  isdrink varchar(5) DEFAULT NULL,
  drinkamount varchar(5) DEFAULT NULL,
  drinkfre varchar(5) DEFAULT NULL,
  sleepstatus varchar(5) DEFAULT NULL,
  sleeptime varchar(5) DEFAULT NULL,
  jobmaterial varchar(5) DEFAULT NULL,
  isjobprotect varchar(5) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE docterinfo (
  id int NOT NULL AUTO_INCREMENT,
  uid int not null,
  height varchar(10) DEFAULT NULL,
  weight varchar(10) DEFAULT NULL,
  gender char(1) DEFAULT NULL,
  hospital varchar(50) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE examination (
  id int NOT NULL AUTO_INCREMENT,
  uid int NOT NULL,
  name varchar(20) DEFAULT NULL,
  gender char(1) DEFAULT NULL,
  age varchar(20) DEFAULT NULL,
  date varchar(20) DEFAULT NULL,
  hospital varchar(20) DEFAULT NULL,
  height varchar(5) DEFAULT NULL,
  weight varchar(5) DEFAULT NULL,
  shousuoya varchar(5) DEFAULT NULL,
  shuzhangya varchar(5) DEFAULT NULL,
  tizhicon varchar(50) DEFAULT NULL,
  neike1 varchar(5) DEFAULT NULL,
  neike2 varchar(15) DEFAULT NULL,
  neike3 varchar(15) DEFAULT NULL,
  neike4 varchar(15) DEFAULT NULL,
  neike5 varchar(15) DEFAULT NULL,
  neike6 varchar(15) DEFAULT NULL,
  neike7 varchar(15) DEFAULT NULL,
  neike8 varchar(15) DEFAULT NULL,
  neike9 varchar(15) DEFAULT NULL,
  neike10 varchar(15) DEFAULT NULL,
  neike11 varchar(15) DEFAULT NULL,
  neike12 varchar(15) DEFAULT NULL,
  neikecon varchar(50) DEFAULT NULL,
  waike1 varchar(15) DEFAULT NULL,
  waike2 varchar(15) DEFAULT NULL,
  waike3 varchar(15) DEFAULT NULL,
  waike4 varchar(15) DEFAULT NULL,
  waike5 varchar(15) DEFAULT NULL,
  waike6 varchar(15) DEFAULT NULL,
  waike7 varchar(15) DEFAULT NULL,
  waike8 varchar(15) DEFAULT NULL,
  waike9 varchar(15) DEFAULT NULL,
  waike10 varchar(15) DEFAULT NULL,
  waike11 varchar(15) DEFAULT NULL,
  waike12 varchar(15) DEFAULT NULL,
  waikecon varchar(50) DEFAULT NULL,
  yanke1 varchar(15) DEFAULT NULL,
  yanke2 varchar(15) DEFAULT NULL,
  yanke3 varchar(15) DEFAULT NULL,
  yanke4 varchar(15) DEFAULT NULL,
  yanke5 varchar(15) DEFAULT NULL,
  yanke6 varchar(15) DEFAULT NULL,
  yanke7 varchar(15) DEFAULT NULL,
  yanke8 varchar(15) DEFAULT NULL,
  yanke9 varchar(15) DEFAULT NULL,
  yanke10 varchar(15) DEFAULT NULL,
  yankecon varchar(50) DEFAULT NULL,
  er varchar(15) DEFAULT NULL,
  bi varchar(15) DEFAULT NULL,
  yan varchar(15) DEFAULT NULL,
  biantaoti varchar(15) DEFAULT NULL,
  hou varchar(15) DEFAULT NULL,
  erbihoucon varchar(50) DEFAULT NULL,
  oral1 varchar(15) DEFAULT NULL,
  oral2 varchar(15) DEFAULT NULL,
  oral3 varchar(15) DEFAULT NULL,
  oralcon varchar(50) DEFAULT NULL,
  ecg1 varchar(5) DEFAULT NULL,
  ecg2 varchar(5) DEFAULT NULL,
  ecg3 varchar(5) DEFAULT NULL,
  ecg4 varchar(5) DEFAULT NULL,
  ecgcon varchar(50) DEFAULT NULL,
  bchaocon varchar(80) DEFAULT NULL,
  fangshe1 varchar(80) DEFAULT NULL,
  fangshecon varchar(50) DEFAULT NULL,
  cancer1 varchar(10) DEFAULT NULL,
  cancer2 varchar(10) DEFAULT NULL,
  cancer3 varchar(10) DEFAULT NULL,
  cancer4 varchar(10) DEFAULT NULL,
  cancer5 varchar(10) DEFAULT NULL,
  cancer6 varchar(10) DEFAULT NULL,
  cancercon varchar(50) DEFAULT NULL,
  blood1 varchar(8) DEFAULT NULL,
  blood2 varchar(8) DEFAULT NULL,
  blood3 varchar(8) DEFAULT NULL,
  blood4 varchar(8) DEFAULT NULL,
  blood5 varchar(8) DEFAULT NULL,
  blood6 varchar(8) DEFAULT NULL,
  blood7 varchar(8) DEFAULT NULL,
  blood8 varchar(8) DEFAULT NULL,
  blood9 varchar(8) DEFAULT NULL,
  blood10 varchar(8) DEFAULT NULL,
  blood11 varchar(8) DEFAULT NULL,
  blood12 varchar(8) DEFAULT NULL,
  blood13 varchar(8) DEFAULT NULL,
  blood14 varchar(8) DEFAULT NULL,
  blood15 varchar(8) DEFAULT NULL,
  blood16 varchar(8) DEFAULT NULL,
  blood17 varchar(8) DEFAULT NULL,
  blood18 varchar(8) DEFAULT NULL,
  blood19 varchar(8) DEFAULT NULL,
  bloodcon varchar(80) DEFAULT NULL,
  urine1 varchar(10) DEFAULT NULL,
  urine2 varchar(10) DEFAULT NULL,
  urine3 varchar(10) DEFAULT NULL,
  urine4 varchar(10) DEFAULT NULL,
  urine5 varchar(10) DEFAULT NULL,
  urine6 varchar(10) DEFAULT NULL,
  urine7 varchar(10) DEFAULT NULL,
  urine8 varchar(10) DEFAULT NULL,
  urine9 varchar(10) DEFAULT NULL,
  urine10 varchar(10) DEFAULT NULL,
  urine11 varchar(10) DEFAULT NULL,
  urine12 varchar(10) DEFAULT NULL,
  urine13 varchar(10) DEFAULT NULL,
  urine14 varchar(10) DEFAULT NULL,
  urine15 varchar(10) DEFAULT NULL,
  urine16 varchar(10) DEFAULT NULL,
  urinecon varchar(80) DEFAULT NULL,
  liver1 varchar(8) DEFAULT NULL,
  liver2 varchar(8) DEFAULT NULL,
  liver3 varchar(8) DEFAULT NULL,
  liver4 varchar(8) DEFAULT NULL,
  liver5 varchar(8) DEFAULT NULL,
  liver6 varchar(8) DEFAULT NULL,
  liver7 varchar(8) DEFAULT NULL,
  liver8 varchar(8) DEFAULT NULL,
  liver9 varchar(8) DEFAULT NULL,
  liver10 varchar(8) DEFAULT NULL,
  liver11 varchar(8) DEFAULT NULL,
  liver12 varchar(8) DEFAULT NULL,
  livercon varchar(80) DEFAULT NULL,
  bloodfat1 varchar(8) DEFAULT NULL,
  bloodfat2 varchar(8) DEFAULT NULL,
  bloodfat3 varchar(8) DEFAULT NULL,
  bloodfat4 varchar(8) DEFAULT NULL,
  bloodfatcon varchar(50) DEFAULT NULL,
  kidney1 varchar(8) DEFAULT NULL,
  kidney2 varchar(8) DEFAULT NULL,
  kidney3 varchar(8) DEFAULT NULL,
  kidneycon varchar(50) DEFAULT NULL,
  xuetang1 varchar(8) DEFAULT NULL,
  xuetangcon varchar(50) DEFAULT NULL,
  summary varchar(200) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE file (
  id int NOT NULL AUTO_INCREMENT,
  uid int  NOT NULL,
  fileaddr varchar(30) NOT NULL,
  filedate varchar(20) NOT NULL,
  fileinfo mediumtext,
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE info (
  id int  NOT NULL AUTO_INCREMENT,
  uid int  NOT NULL,
  date varchar(20) NOT NULL,
  xinlv int DEFAULT NULL,
  xdgs char(10) DEFAULT NULL,
  con1 char(2) DEFAULT NULL,
  sxxdgs char(10) DEFAULT NULL,
  con2 char(2) DEFAULT NULL,
  xdgh char(10) DEFAULT NULL,
  con3 char(2) DEFAULT NULL,
  fxyb char(10) DEFAULT NULL,
  con4 char(2) DEFAULT NULL,
  sxyb char(10) DEFAULT NULL,
  con5 char(2) DEFAULT NULL,
  xlbq char(10) DEFAULT NULL,
  con6 char(2) DEFAULT NULL,
  sxzb char(10) DEFAULT NULL,
  con7 char(2) DEFAULT NULL,
  fxzb char(10) DEFAULT NULL,
  con8 char(2) DEFAULT NULL,
  jjxzb char(10) DEFAULT NULL,
  con9 char(2) DEFAULT NULL,
  fc char(10) DEFAULT NULL,
  con10 char(2) DEFAULT NULL,
  data mediumtext,
  pr CHAR (5),
  qrs CHAR (5),
  qt CHAR (5),
  qtc CHAR (5),
  p CHAR (5),
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE info24 (
  id int  NOT NULL AUTO_INCREMENT,
  uid int  NOT NULL,
  date varchar(20) NOT NULL,
  time int NOT NULL,
  dataaddr varchar(30) NOT NULL,
  conclusion mediumtext NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE medicalhistory (
  id int  NOT NULL AUTO_INCREMENT,
  uid int  NOT NULL,
  city varchar(30) NOT NULL,
  date varchar(20) NOT NULL,
  hospital varchar(20) NOT NULL,
  office varchar(10) NOT NULL,
  doctor varchar(10) NOT NULL,
  conclusion varchar(200) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE suggestion (
  id int  NOT NULL AUTO_INCREMENT,
  uid int  NOT NULL,
  date varchar(20) NOT NULL,
  suggestion varchar(240) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_rela (
  id int  NOT NULL AUTO_INCREMENT,
  uid int  NOT NULL,
  reid int  NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid),
  FOREIGN KEY (reid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create table friend_request(
  id int not null AUTO_INCREMENT,
  uid int  NOT NULL ,
  reid int NOT NULL ,
  status tinyint(1) NOT NULL,
  information varchar(100) DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (uid) REFERENCES user(uid),
  FOREIGN KEY (reid) REFERENCES user(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;